// Code generated by protoc-gen-cmdid. DO NOT EDIT.
// versions:
// 	protoc-gen-cmdid v1.0.0
// 	protoc           v4.24.2
// source: test.proto

package protos

import (
	cmd "protoc-gen-cmdid/examples/cmd"
)

const (
	SearchRequest_CmdId   uint16 = 1
	SearchRequest_CmdName string = "SearchRequest"
)

func (cmd *SearchRequest) CmdId() uint16   { return SearchRequest_CmdId }
func (cmd *SearchRequest) CmdName() string { return SearchRequest_CmdName }
func init()                                { cmd.RegisterCmd(func() cmd.CmdMessage { return new(SearchRequest) }) }

const (
	SearchResponse_CmdId   uint16 = 2
	SearchResponse_CmdName string = "SearchResponse"
)

func (cmd *SearchResponse) CmdId() uint16   { return SearchResponse_CmdId }
func (cmd *SearchResponse) CmdName() string { return SearchResponse_CmdName }
func init()                                 { cmd.RegisterCmd(func() cmd.CmdMessage { return new(SearchResponse) }) }

const (
	SearchResponse_NestedData_CmdId   uint16 = 3
	SearchResponse_NestedData_CmdName string = "SearchResponse_NestedData"
)

func (cmd *SearchResponse_NestedData) CmdId() uint16   { return SearchResponse_NestedData_CmdId }
func (cmd *SearchResponse_NestedData) CmdName() string { return SearchResponse_NestedData_CmdName }
func init()                                            { cmd.RegisterCmd(func() cmd.CmdMessage { return new(SearchResponse_NestedData) }) }
