// Code generated by protoc-gen-cmdid. DO NOT EDIT.
// versions:
// 	protoc-gen-cmdid v1.0.0
// 	protoc           v4.24.2
// source: test.proto

package protos

import (
	protocmd "github.com/stalomeow/protocmd"
)

const (
	TestReq_CmdId   uint16 = 1010
	TestReq_CmdName string = "TestReq"
)

func (*TestReq) CmdId() uint16   { return TestReq_CmdId }
func (*TestReq) CmdName() string { return TestReq_CmdName }

const (
	TestRsp_CmdId   uint16 = 1011
	TestRsp_CmdName string = "TestRsp"
)

func (*TestRsp) CmdId() uint16   { return TestRsp_CmdId }
func (*TestRsp) CmdName() string { return TestRsp_CmdName }

const (
	TestRsp_TransformInfo_CmdId   uint16 = 2010
	TestRsp_TransformInfo_CmdName string = "TestRsp_TransformInfo"
)

func (*TestRsp_TransformInfo) CmdId() uint16   { return TestRsp_TransformInfo_CmdId }
func (*TestRsp_TransformInfo) CmdName() string { return TestRsp_TransformInfo_CmdName }

func init() {
	protocmd.Register(func() protocmd.CmdMessage { return new(TestReq) })
	protocmd.Register(func() protocmd.CmdMessage { return new(TestRsp) })
	protocmd.Register(func() protocmd.CmdMessage { return new(TestRsp_TransformInfo) })
}
