// <auto-generated>
//     Generated by protoc-gen-cmd v1.0.0.  DO NOT EDIT!
//     source: test.proto
// </auto-generated>

using pb = global::Google.Protobuf;

namespace Examples.CSharp.Protos
{
    partial class TestReq : pb::ICmdMessage
    {
        public static ushort CmdId { get { return 1010; } }
        ushort pb::ICmdMessage.CmdId { get { return 1010; } }

        public static string CmdName { get { return "TestReq"; } }
        string pb::ICmdMessage.CmdName { get { return "TestReq"; } }
    }
    partial class TestRsp : pb::ICmdMessage
    {
        public static ushort CmdId { get { return 1011; } }
        ushort pb::ICmdMessage.CmdId { get { return 1011; } }

        public static string CmdName { get { return "TestRsp"; } }
        string pb::ICmdMessage.CmdName { get { return "TestRsp"; } }

        partial class Types
        {
            partial class TransformInfo : pb::ICmdMessage
            {
                public static ushort CmdId { get { return 2010; } }
                ushort pb::ICmdMessage.CmdId { get { return 2010; } }

                public static string CmdName { get { return "TransformInfo"; } }
                string pb::ICmdMessage.CmdName { get { return "TransformInfo"; } }
            }
        }
    }
}
